name: remote-sensing-landuse
channels:
  - pytorch
  - conda-forge
  - defaults
dependencies:
  - blas=1.0
  - blosc=1.21.1
  - boost-cpp=1.78.0
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2022.10.11
  - cairo=1.16.0
  - certifi=2022.9.24
  - cffi=1.15.1
  - cfitsio=4.2.0
  - cryptography=38.0.1
  - curl=7.86.0
  - expat=2.5.0
  - ffmpeg=4.3
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.1
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - freexl=1.0.6
  - future=0.18.2
  - gdal=3.6.0
  - geos=3.11.1
  - geotiff=1.7.1
  - gettext=0.21.1
  - giflib=5.2.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - hdf4=4.2.15
  - hdf5=1.12.2
  - icu=70.1
  - idna=3.4
  - intel-openmp=2021.4.0
  - jpeg=9e
  - json-c=0.16
  - kealib=1.5.0
  - krb5=1.19.3
  - lame=3.100
  - lcms2=2.14
  - lerc=4.0.0
  - libcurl=7.86.0
  - libcxx=14.0.6
  - libdeflate=1.14
  - libedit=3.1.20191231
  - libev=4.33
  - libffi=3.4.2
  - libgdal=3.6.0
#  - libgfortran=5.0.0
#  - libgfortran5=11.3.0
  - libglib=2.74.1
  - libiconv=1.17
  - libidn2=2.3.2
  - libkml=1.3.0
  - libnetcdf=4.8.1
  - libnghttp2=1.47.0
  - libpng=1.6.39
  - libpq=15.1
  - librttopo=1.1.0
  - libspatialite=5.0.1
  - libsqlite=3.40.0
  - libssh2=1.10.0
  - libtasn1=4.16.0
  - libtiff=4.4.0
  - libunistring=0.9.10
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.10.3
  - libzip=1.9.2
  - libzlib=1.2.13
  - llvm-openmp=15.0.5
  - lz4-c=1.9.3
  - mkl=2021.4.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.1
  - mkl_random=1.2.2
  - ncurses=6.3
  - nettle=3.7.3
  - ninja=1.10.2
  - ninja-base=1.10.2
  - nspr=4.35
  - nss=3.78
  - numpy=1.23.4
  - numpy-base=1.23.4
  - openh264=2.1.1
  - openjpeg=2.5.0
  - openssl=3.0.7
  - pcre2=10.40
  - pip=22.3.1
  - pixman=0.40.0
  - poppler=22.11.0
  - poppler-data=0.4.11
  - postgresql=15.1
  - proj=9.1.0
  - pycparser=2.21
  - pyopenssl=22.0.0
  - pysocks=1.7.1
  - python=3.8.15
  - python_abi=3.8
  - pytorch=1.13.0
  - qhull=2020.2
  - readline=8.1.2
  - requests=2.28.1
  - setuptools=65.5.1
  - six=1.16.0
  - snappy=1.1.9
  - sqlite=3.40.0
  - tiledb=2.11.3
  - tk=8.6.12
  - torchvision=0.14.0
  - typing_extensions=4.3.0
  - tzcode=2022g
  - tzdata=2022g
  - urllib3=1.26.12
  - wheel=0.38.4
  - xerces-c=3.2.4
  - xz=5.2.6
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
    - absl-py==1.3.0
    - aiohttp==3.8.3
    - aiosignal==1.3.1
    - anyio==3.6.2
    - appnope==0.1.3
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asttokens==2.1.0
    - async-timeout==4.0.2
    - attrs==22.1.0
    - babel==2.11.0
    - backcall==0.2.0
    - beautifulsoup4==4.11.1
    - bleach==5.0.1
    - boto3==1.26.19
    - botocore==1.29.19
    - bqplot==0.12.36
    - branca==0.6.0
    - cachetools==5.2.0
    - charset-normalizer==2.1.1
    - click==8.1.3
    - colour==0.1.5
    - contourpy==1.0.6
    - cycler==0.11.0
    - debugpy==1.6.3
    - decorator==5.1.1
    - defusedxml==0.7.1
    - earthengine-api==0.1.331
    - ee-extra==0.0.14
    - entrypoints==0.4
    - executing==1.2.0
    - fastjsonschema==2.16.2
    - ffmpeg-python==0.2.0
    - filelock==3.8.0
    - fire==0.4.0
    - folium==0.13.0
    - fonttools==4.38.0
    - frozenlist==1.3.3
    - fsspec==2022.11.0
    - gcloud==0.18.3
    - gdown==4.5.3
    - geeadd==0.5.6
    - geemap==0.17.2
    - geocoder==1.38.1
    - geojson==2.5.0
    - google-api-core==2.10.2
    - google-api-python-client==2.65.0
    - google-auth==2.14.1
    - google-auth-httplib2==0.1.0
    - google-auth-oauthlib==0.4.6
    - google-cloud-core==2.3.2
    - google-cloud-storage==2.6.0
    - google-crc32c==1.5.0
    - google-resumable-media==2.4.0
    - googleapis-common-protos==1.56.4
    - grpcio==1.50.0
    - httplib2==0.21.0
    - humanfriendly==10.0
    - imageio==2.22.4
    - importlib-metadata==5.0.0
    - importlib-resources==5.10.0
    - ipyevents==2.0.1
    - ipyfilechooser==0.6.0
    - ipykernel==6.17.1
    - ipyleaflet==0.17.2
    - ipython==8.6.0
    - ipython-genutils==0.2.0
    - ipytree==0.2.2
    - ipywidgets==8.0.2
    - jedi==0.18.1
    - jinja2==3.1.2
    - jmespath==1.0.1
    - joblib==1.2.0
    - json5==0.9.10
    - jsonschema==4.17.0
    - jupyter-client==7.4.5
    - jupyter-core==5.0.0
    - jupyter-server==1.23.2
    - jupyterlab==3.5.0
    - jupyterlab-pygments==0.2.2
    - jupyterlab-server==2.16.3
    - jupyterlab-widgets==3.0.3
    - kiwisolver==1.4.4
    - lightning-utilities==0.3.0
    - llvmlite==0.39.1
    - logzero==1.7.0
    - markdown==3.4.1
    - markupsafe==2.1.1
    - matplotlib==3.6.2
    - matplotlib-inline==0.1.6
    - mistune==2.0.4
    - multidict==6.0.2
    - nbclassic==0.4.8
    - nbclient==0.7.0
    - nbconvert==7.2.5
    - nbformat==5.7.0
    - nest-asyncio==1.5.6
    - networkx==2.8.8
    - notebook==6.5.2
    - notebook-shim==0.2.2
    - numba==0.56.4
    - oauth2client==4.1.3
    - oauthlib==3.2.2
    - opencv-python==4.6.0.66
    - packaging==21.3
    - pandas==1.5.1
    - pandocfilters==1.5.0
    - parso==0.8.3
    - pexpect==4.8.0
    - pickleshare==0.7.5
    - pillow==9.3.0
    - pkgutil-resolve-name==1.3.10
    - platformdirs==2.5.4
    - plotly==5.11.0
    - prometheus-client==0.15.0
    - prompt-toolkit==3.0.32
    - protobuf==3.20.3
    - psutil==5.9.4
    - ptyprocess==0.7.0
    - pure-eval==0.2.2
    - pyasn1==0.4.8
    - pyasn1-modules==0.2.8
    - pycrs==1.0.2
    - pygments==2.13.0
    - pynndescent==0.5.8
    - pyparsing==3.0.9
    - pyrsistent==0.19.2
    - pyshp==2.3.1
    - python-box==6.1.0
    - python-dateutil==2.8.2
    - pytorch-lightning==1.8.1
    - pytz==2022.6
    - pywavelets==1.4.1
    - pyyaml==6.0
    - pyzmq==24.0.1
    - ratelim==0.1.6
    - requests-auth==6.0.0
    - requests-oauthlib==1.3.1
    - rsa==4.9
    - s3transfer==0.6.0
    - sankee==0.2.0
    - scikit-image==0.19.3
    - scikit-learn==1.1.3
    - scipy==1.9.3
    - scooby==0.7.0
    - seaborn==0.12.1
    - send2trash==1.8.0
    - shapely==1.8.5.post1
    - sniffio==1.3.0
    - soupsieve==2.3.2.post1
    - stack-data==0.6.1
    - tenacity==8.1.0
    - tensorboard==2.11.0
    - tensorboard-data-server==0.6.1
    - tensorboard-plugin-wit==1.8.1
    - termcolor==2.1.0
    - terminado==0.17.0
  #  - terracatalogueclient==0.1.14
    - threadpoolctl==3.1.0
    - tifffile==2022.10.10
    - tinycss2==1.2.1
    - tomli==2.0.1
    - torch==1.13.0
    - torchaudio==0.13.0
    - torchmetrics==0.10.2
    - torchscan==0.1.2
    - tornado==6.2
    - tqdm==4.64.1
    - traitlets==5.5.0
    - traittypes==0.2.1
    - typing-extensions==4.4.0
    - umap-learn==0.5.3
    - uritemplate==4.1.1
    - wcwidth==0.2.5
    - webencodings==0.5.1
    - websocket-client==1.4.2
    - werkzeug==2.2.2
    - whitebox==2.2.0
    - whiteboxgui==2.2.0
    - widgetsnbextension==4.0.3
    - xyzservices==2022.9.0
    - yarl==1.8.1
    - zipp==3.10.0
